// src/database.ts
import {
    Humidifiers,
    type HumidifierType,
    Lights,
    type LightType,
    type MushroomChildId,
    MushroomChildIds,
    type MushroomDef,
    SpecialConditions,
    TimeRanges,
    Woods,
    type WoodType
} from './types';


export const MUSHROOM_CHILDREN: Record<MushroomChildId, string> = {
    [MushroomChildIds.CAO]: '草帽菌',
    [MushroomChildIds.CI]: '刺头菌',
    [MushroomChildIds.MAO]: '猫爪菌',
    [MushroomChildIds.PAO]: '泡泡菌',
    [MushroomChildIds.SHAN_HU]: '珊瑚菌',
    [MushroomChildIds.LABA]: '喇叭菌',
    [MushroomChildIds.DI]: '地星菌',
    [MushroomChildIds.DEER]: '鹿角菌',
    [MushroomChildIds.CAI]: '菜菜菌',
    [MushroomChildIds.GHOST]: '幽灵菌',
    [MushroomChildIds.NIAO]: '鸟巢菌',
    [MushroomChildIds.LING]: '美灵芝',
    [MushroomChildIds.ZHU]: '竹荪',
    [MushroomChildIds.RUBY]: '宝石菌',
    [MushroomChildIds.HOU]: '猴头菌',
}


// --- 新增：道具详情信息 (来源) ---

export const WOOD_INFO: Record<WoodType, { source: string }> = {
    [Woods.BAI]: {source: '1级'},
    [Woods.FENG]: {source: '商店出现'},
    [Woods.SONG]: {source: '6级'},
    [Woods.CHANG_CHUN]: {source: '7级'},
    [Woods.GE_TENG]: {source: '9级'},
    [Woods.JIAN_CI]: {source: '10级'},
    [Woods.JIAN_JING]: {source: '12级'},
    [Woods.LV_SONG]: {source: '13级'},
    [Woods.GOLD]: {source: '15级'},
    [Woods.LOVE]: {source: '白龙1'},
    [Woods.QIAN_NIU]: {source: '白龙1'},
    [Woods.QING]: {source: '白龙2'},
    [Woods.YAN]: {source: '白龙2'},
    [Woods.MING]: {source: '白龙3'},
    [Woods.SHU]: {source: '白龙3'},
};

export const LIGHT_INFO: Record<LightType, { source: string }> = {
    [Lights.HUO]: {source: '2级'},
    [Lights.HUN]: {source: '5级'},
    [Lights.TONG]: {source: '11级'},
    [Lights.YU_RONG]: {source: '白龙2'},
    [Lights.DRAGON]: {source: '白龙3'},
};

export const HUMIDIFIER_INFO: Record<HumidifierType, { source: string }> = {
    [Humidifiers.ZHU]: {source: '4级'},
    [Humidifiers.LIAN]: {source: '8级'},
    [Humidifiers.TAO]: {source: '14级'},
    [Humidifiers.NIAO]: {source: '白龙1'},
    [Humidifiers.BLUE]: {source: '白龙3'},
};

const CI_MUSHROOMS: MushroomDef[] = [
    {
        id: 'ci0',
        name: '未能长大的刺头菌',
        pinyin: 'wnzddctj',
        starter: MushroomChildIds.CI,
        special: SpecialConditions.BUG,
        save: false,
    },
    {
        id: 'ci1',
        name: '中等善良刺头菌',
        pinyin: 'zdslctj',
        starter: MushroomChildIds.CI,
        wood: Woods.BAI,
        light: Lights.HUO,
    },
    {
        id: 'ci2',
        name: '中等邪恶刺头菌',
        pinyin: 'zdxectj',
        starter: MushroomChildIds.CI,
        wood: Woods.BAI,
        light: Lights.HUO,
        special: SpecialConditions.LESS,
        save: true
    },
    {
        id: 'ci3',
        name: '中等寒冰刺头菌',
        pinyin: 'zdhbctj',
        starter: MushroomChildIds.CI,
        wood: Woods.BAI,
        light: Lights.HUO,
        special: SpecialConditions.MUCH,
        save: true
    },
    {
        id: 'ci4',
        name: '袖珍邪恶刺头菌',
        pinyin: 'xzxectj',
        starter: MushroomChildIds.CI,
        wood: Woods.QIAN_NIU,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'ci5',
        name: '中等荧光刺头菌',
        pinyin: 'zdygctj',
        starter: MushroomChildIds.CI,
        wood: Woods.QIAN_NIU,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true
    },
    {
        id: 'ci6',
        name: '巨巨邪恶刺头菌',
        pinyin: 'jjxectj',
        starter: MushroomChildIds.CI,
        wood: Woods.QIAN_NIU,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true
    },
    {
        id: 'ci7',
        name: '中等太白金星刺头菌',
        pinyin: 'zdtbjxctj',
        starter: MushroomChildIds.CI,
        wood: Woods.JIAN_CI,
    },
    {
        id: 'ci8',
        name: '中等魔法少女刺头菌',
        pinyin: 'zdmfsnctj',
        starter: MushroomChildIds.CI,
        wood: Woods.JIAN_CI,
        special: SpecialConditions.LESS,
        save: true
    },
    {
        id: 'ci9',
        name: '袖珍小荧光刺头菌',
        pinyin: 'xzxygctj',
        starter: MushroomChildIds.CI,
        wood: Woods.JIAN_CI,
        special: SpecialConditions.MUCH,
        save: true
    },
    {
        id: 'ci10',
        name: '袖珍善良刺头菌',
        pinyin: 'xzslctj',
        starter: MushroomChildIds.CI,
        wood: Woods.JIAN_CI,
        light: Lights.HUO,
    },
    {
        id: 'ci11',
        name: '巨巨荧光刺头菌',
        pinyin: 'jjygctj',
        starter: MushroomChildIds.CI,
        wood: Woods.JIAN_CI,
        light: Lights.HUO,
        special: SpecialConditions.LESS,
        save: true
    },
    {
        id: 'ci12',
        name: '袖珍魔法少女刺头菌',
        pinyin: 'xzmfsnctj',
        starter: MushroomChildIds.CI,
        wood: Woods.JIAN_CI,
        light: Lights.HUO,
        special: SpecialConditions.MUCH,
        save: true
    },
    {
        id: 'ci13',
        name: '巨巨魔法少女刺头菌',
        pinyin: 'jjmfsnctj',
        starter: MushroomChildIds.CI,
        wood: Woods.JIAN_JING,
        light: Lights.TONG,
        humidifier: Humidifiers.BLUE,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'ci14',
        name: '巨巨善良刺头菌',
        pinyin: 'jjslctj',
        starter: MushroomChildIds.CI,
        wood: Woods.JIAN_JING,
        light: Lights.TONG,
        humidifier: Humidifiers.BLUE,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true
    },
    {
        id: 'ci15',
        name: '袖珍寒冰刺头菌',
        pinyin: 'xzhbctj',
        starter: MushroomChildIds.CI,
        wood: Woods.JIAN_JING,
        light: Lights.TONG,
        humidifier: Humidifiers.BLUE,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true
    },
    {
        id: 'ci16',
        name: '巨巨寒冰刺头菌',
        pinyin: 'jjhbctj',
        starter: MushroomChildIds.CI,
        wood: Woods.LV_SONG,
    },
    {
        id: 'ci17',
        name: '袖珍太白金星刺头菌',
        pinyin: 'xztbjxctj',
        starter: MushroomChildIds.CI,
        wood: Woods.LV_SONG,
        special: SpecialConditions.LESS,
        save: true
    },
    {
        id: 'ci18',
        name: '巨巨太白金星刺头菌',
        pinyin: 'jjtbjxctj',
        starter: MushroomChildIds.CI,
        wood: Woods.LV_SONG,
        special: SpecialConditions.MUCH,
        save: true
    },
];

const MAO_MUSHROOMS: MushroomDef[] = [
    {
        id: 'mao0',
        name: '未能长大的猫爪菌',
        pinyin: 'wnzddmzj',
        starter: MushroomChildIds.MAO,
        special: SpecialConditions.BUG,
        save: false,
    },
    {
        id: 'mao1',
        name: '一般傲娇猫爪菌',
        pinyin: 'ybajmzj',
        starter: MushroomChildIds.MAO,
        wood: Woods.BAI,
        light: Lights.HUO,
    },
    {
        id: 'mao2',
        name: '一般萌萌猫爪菌',
        pinyin: 'ybmmmzj',
        starter: MushroomChildIds.MAO,
        wood: Woods.BAI,
        light: Lights.HUO,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'mao3',
        name: '一般暗黑猫爪菌',
        pinyin: 'ybahmzj',
        starter: MushroomChildIds.MAO,
        wood: Woods.BAI,
        light: Lights.HUO,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'mao4',
        name: '迷你萌萌猫爪菌',
        pinyin: 'mnmmmzj',
        starter: MushroomChildIds.MAO,
        wood: Woods.QIAN_NIU,
        light: Lights.HUO,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'mao5',
        name: '一般凑凑猫爪菌',
        pinyin: 'ybccmzj',
        starter: MushroomChildIds.MAO,
        wood: Woods.QIAN_NIU,
        light: Lights.HUO,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'mao6',
        name: '巨大萌萌猫爪菌',
        pinyin: 'jdmmmzj',
        starter: MushroomChildIds.MAO,
        wood: Woods.QIAN_NIU,
        light: Lights.HUO,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'mao7',
        name: '一般撞色猫爪菌',
        pinyin: 'ybzsmzj',
        starter: MushroomChildIds.MAO,
        wood: Woods.JIAN_CI,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
    },
    {
        id: 'mao8',
        name: '一般红温猫爪菌',
        pinyin: 'ybhwmzj',
        starter: MushroomChildIds.MAO,
        wood: Woods.JIAN_CI,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'mao9',
        name: '迷你凑凑猫爪菌',
        pinyin: 'mnccmzj',
        starter: MushroomChildIds.MAO,
        wood: Woods.JIAN_CI,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'mao10',
        name: '迷你傲娇猫爪菌',
        pinyin: 'mnajmzj',
        starter: MushroomChildIds.MAO,
        wood: Woods.JIAN_CI,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
    },
    {
        id: 'mao11',
        name: '巨大凑凑猫爪菌',
        pinyin: 'jdccmzj',
        starter: MushroomChildIds.MAO,
        wood: Woods.JIAN_CI,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'mao12',
        name: '迷你红温猫爪菌',
        pinyin: 'mnhwmzj',
        starter: MushroomChildIds.MAO,
        wood: Woods.JIAN_CI,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'mao13',
        name: '巨大红温猫爪菌',
        pinyin: 'jdhwmzj',
        starter: MushroomChildIds.MAO,
        wood: Woods.LV_SONG,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.TAO,
    },
    {
        id: 'mao14',
        name: '巨大傲娇猫爪菌',
        pinyin: 'jdajmzj',
        starter: MushroomChildIds.MAO,
        wood: Woods.LV_SONG,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.TAO,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'mao15',
        name: '迷你暗黑猫爪菌',
        pinyin: 'mnahmzj',
        starter: MushroomChildIds.MAO,
        wood: Woods.LV_SONG,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.TAO,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'mao16',
        name: '巨大暗黑猫爪菌',
        pinyin: 'jdahmzj',
        starter: MushroomChildIds.MAO,
        wood: Woods.LV_SONG,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
    },
    {
        id: 'mao17',
        name: '迷你撞色猫爪菌',
        pinyin: 'mnzsmzj',
        starter: MushroomChildIds.MAO,
        wood: Woods.LV_SONG,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'mao18',
        name: '巨大撞色猫爪菌',
        pinyin: 'jdzsmzj',
        starter: MushroomChildIds.MAO,
        wood: Woods.LV_SONG,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
];

const PAO_MUSHROOMS: MushroomDef[] = [
    {
        id: 'pao0',
        name: '未能长大的泡泡菌',
        pinyin: 'wnzddppj',
        starter: MushroomChildIds.PAO,
        special: SpecialConditions.BUG,
        save: false,
    },
    {
        id: 'pao1',
        name: '常见实习泡泡菌',
        pinyin: 'cjsxppj',
        starter: MushroomChildIds.PAO,
        wood: Woods.BAI,
    },
    {
        id: 'pao2',
        name: '常见新手泡泡菌',
        pinyin: 'cjxsppj',
        starter: MushroomChildIds.PAO,
        wood: Woods.BAI,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'pao3',
        name: '常见菜色泡泡菌',
        pinyin: 'cjcsppj',
        starter: MushroomChildIds.PAO,
        wood: Woods.BAI,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'pao4',
        name: '常见看破一切泡泡菌',
        pinyin: 'cjkpyqppj',
        starter: MushroomChildIds.PAO,
        wood: Woods.LOVE,
        light: Lights.HUO,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'pao5',
        name: '常见过劳泡泡菌',
        pinyin: 'cjglppj',
        starter: MushroomChildIds.PAO,
        wood: Woods.LOVE,
        light: Lights.HUO,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'pao6',
        name: '超小亚健康泡泡菌',
        pinyin: 'cxyjkppj',
        starter: MushroomChildIds.PAO,
        wood: Woods.LOVE,
        light: Lights.HUO,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'pao7',
        name: '超小实习泡泡菌',
        pinyin: 'cxsxppj',
        starter: MushroomChildIds.PAO,
        wood: Woods.LOVE,
        light: Lights.HUN,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'pao8',
        name: '超大亚健康泡泡菌',
        pinyin: 'cdyjkppj',
        starter: MushroomChildIds.PAO,
        wood: Woods.LOVE,
        light: Lights.HUN,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'pao9',
        name: '超小过劳泡泡菌',
        pinyin: 'cxglppj',
        starter: MushroomChildIds.PAO,
        wood: Woods.LOVE,
        light: Lights.HUN,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'pao10',
        name: '超小新手泡泡菌',
        pinyin: 'cxxsppj',
        starter: MushroomChildIds.PAO,
        wood: Woods.QIAN_NIU,
        light: Lights.HUN,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
    },
    {
        id: 'pao11',
        name: '常见亚健康泡泡菌',
        pinyin: 'cjyjkppj',
        starter: MushroomChildIds.PAO,
        wood: Woods.QIAN_NIU,
        light: Lights.HUN,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'pao12',
        name: '超大新手泡泡菌',
        pinyin: 'cdxsppj',
        starter: MushroomChildIds.PAO,
        wood: Woods.QIAN_NIU,
        light: Lights.HUN,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'pao13',
        name: '超大过劳泡泡菌',
        pinyin: 'cdglppj',
        starter: MushroomChildIds.PAO,
        wood: Woods.JIAN_JING,
        light: Lights.HUO,
        time: TimeRanges.DAY,
    },
    {
        id: 'pao14',
        name: '超大实习泡泡菌',
        pinyin: 'cdsxppj',
        starter: MushroomChildIds.PAO,
        wood: Woods.JIAN_JING,
        light: Lights.HUO,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'pao15',
        name: '超小菜色泡泡菌',
        pinyin: 'cxcsppj',
        starter: MushroomChildIds.PAO,
        wood: Woods.JIAN_JING,
        light: Lights.HUO,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'pao16',
        name: '超大菜色泡泡菌',
        pinyin: 'cdcsppj',
        starter: MushroomChildIds.PAO,
        wood: Woods.JIAN_JING,
        light: Lights.HUO,
        humidifier: Humidifiers.NIAO,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'pao17',
        name: '超小看破一切泡泡菌',
        pinyin: 'cxkpyqppj',
        starter: MushroomChildIds.PAO,
        wood: Woods.JIAN_JING,
        light: Lights.HUO,
        humidifier: Humidifiers.NIAO,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'pao18',
        name: '超大看破一切泡泡菌',
        pinyin: 'cdkpyqppj',
        starter: MushroomChildIds.PAO,
        wood: Woods.JIAN_JING,
        light: Lights.HUO,
        humidifier: Humidifiers.NIAO,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
];

const CAO_MUSHROOMS: MushroomDef[] = [
    {
        id: 'cao0',
        name: '未能长大的草帽菌',
        pinyin: 'wnzddcmj',
        starter: MushroomChildIds.CAO,
        special: SpecialConditions.BUG,
        save: false,
    },
    {
        id: 'cao1',
        name: '普通老土草帽菌',
        pinyin: 'ptltcmj',
        starter: MushroomChildIds.CAO,
        wood: Woods.BAI,
    },
    {
        id: 'cao2',
        name: '普通洁癖草帽菌',
        pinyin: 'ptjpcmj',
        starter: MushroomChildIds.CAO,
        wood: Woods.BAI,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'cao3',
        name: '普通健美草帽菌',
        pinyin: 'ptjmcmj',
        starter: MushroomChildIds.CAO,
        wood: Woods.BAI,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'cao4',
        name: '普通恶毒草帽菌',
        pinyin: 'ptedcmj',
        starter: MushroomChildIds.CAO,
        wood: Woods.LOVE,
        light: Lights.HUN,
        time: TimeRanges.DAY,
    },
    {
        id: 'cao5',
        name: '普通蓝瘦草帽菌',
        pinyin: 'ptlscmj',
        starter: MushroomChildIds.CAO,
        wood: Woods.LOVE,
        light: Lights.HUN,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'cao6',
        name: '小斑比草帽菌',
        pinyin: 'xbbcmj',
        starter: MushroomChildIds.CAO,
        wood: Woods.LOVE,
        light: Lights.HUN,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'cao7',
        name: '小老土草帽菌',
        pinyin: 'xltcmj',
        starter: MushroomChildIds.CAO,
        wood: Woods.LOVE,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'cao8',
        name: '大斑比草帽菌',
        pinyin: 'dbbcmj',
        starter: MushroomChildIds.CAO,
        wood: Woods.LOVE,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'cao9',
        name: '小蓝瘦草帽菌',
        pinyin: 'xlscmj',
        starter: MushroomChildIds.CAO,
        wood: Woods.LOVE,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'cao10',
        name: '小洁癖草帽菌',
        pinyin: 'xjpcmj',
        starter: MushroomChildIds.CAO,
        wood: Woods.QIAN_NIU,
        light: Lights.HUO,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
    },
    {
        id: 'cao11',
        name: '普通斑比草帽菌',
        pinyin: 'ptbbcmj',
        starter: MushroomChildIds.CAO,
        wood: Woods.QIAN_NIU,
        light: Lights.HUO,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'cao12',
        name: '大洁癖草帽菌',
        pinyin: 'djpcmj',
        starter: MushroomChildIds.CAO,
        wood: Woods.QIAN_NIU,
        light: Lights.HUO,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'cao13',
        name: '大健美草帽菌',
        pinyin: 'djmcmj',
        starter: MushroomChildIds.CAO,
        wood: Woods.JIAN_JING,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
    },
    {
        id: 'cao14',
        name: '小恶毒草帽菌',
        pinyin: 'xedcmj',
        starter: MushroomChildIds.CAO,
        wood: Woods.JIAN_JING,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'cao15',
        name: '大恶毒草帽菌',
        pinyin: 'dedcmj',
        starter: MushroomChildIds.CAO,
        wood: Woods.JIAN_JING,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'cao16',
        name: '大蓝瘦草帽菌',
        pinyin: 'dlscmj',
        starter: MushroomChildIds.CAO,
        wood: Woods.JIAN_JING,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
    },
    {
        id: 'cao17',
        name: '大老土草帽菌',
        pinyin: 'dltcmj',
        starter: MushroomChildIds.CAO,
        wood: Woods.JIAN_JING,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'cao18',
        name: '小健美草帽菌',
        pinyin: 'xjmcmj',
        starter: MushroomChildIds.CAO,
        wood: Woods.JIAN_JING,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
];

const SHANHU_MUSHROOMS: MushroomDef[] = [
    {
        id: 'shanhu0',
        name: '未能长大的珊瑚菌',
        pinyin: 'wnzddshj',
        starter: MushroomChildIds.SHAN_HU,
        special: SpecialConditions.BUG,
        save: false,
    },
    {
        id: 'shanhu1',
        name: '中级贾诩珊瑚菌',
        pinyin: 'zjjxshj',
        starter: MushroomChildIds.SHAN_HU,
        wood: Woods.FENG,
    },
    {
        id: 'shanhu2',
        name: '中级公孙珊珊瑚菌',
        pinyin: 'zjgssshj',
        starter: MushroomChildIds.SHAN_HU,
        wood: Woods.FENG,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'shanhu3',
        name: '中级董奉珊瑚菌',
        pinyin: 'zjdfshj',
        starter: MushroomChildIds.SHAN_HU,
        wood: Woods.FENG,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'shanhu4',
        name: '缩水公孙珊珊瑚菌',
        pinyin: 'ssgssshj',
        starter: MushroomChildIds.SHAN_HU,
        wood: Woods.GE_TENG,
    },
    {
        id: 'shanhu5',
        name: '中级张郃珊瑚菌',
        pinyin: 'zjzhshj',
        starter: MushroomChildIds.SHAN_HU,
        wood: Woods.GE_TENG,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'shanhu6',
        name: '膨胀公孙珊珊瑚菌',
        pinyin: 'pzgssshj',
        starter: MushroomChildIds.SHAN_HU,
        wood: Woods.GE_TENG,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'shanhu7',
        name: '中级戏学珊瑚菌',
        pinyin: 'zjxxshj',
        starter: MushroomChildIds.SHAN_HU,
        wood: Woods.JIAN_CI,
        light: Lights.HUN,
        time: TimeRanges.DAY,
    },
    {
        id: 'shanhu8',
        name: '中级陈登珊瑚菌',
        pinyin: 'zjcdshj',
        starter: MushroomChildIds.SHAN_HU,
        wood: Woods.JIAN_CI,
        light: Lights.HUN,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'shanhu9',
        name: '缩水张郃珊瑚菌',
        pinyin: 'sszhshj',
        starter: MushroomChildIds.SHAN_HU,
        wood: Woods.JIAN_CI,
        light: Lights.HUN,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'shanhu10',
        name: '膨胀董奉珊瑚菌',
        pinyin: 'pzdfshj',
        starter: MushroomChildIds.SHAN_HU,
        wood: Woods.LV_SONG,
        light: Lights.HUO,
        time: TimeRanges.DAY,
    },
    {
        id: 'shanhu11',
        name: '缩水戏学珊瑚菌',
        pinyin: 'ssxxshj',
        starter: MushroomChildIds.SHAN_HU,
        wood: Woods.LV_SONG,
        light: Lights.HUO,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'shanhu12',
        name: '膨胀戏学珊瑚菌',
        pinyin: 'pzxxshj',
        starter: MushroomChildIds.SHAN_HU,
        wood: Woods.LV_SONG,
        light: Lights.HUO,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'shanhu13',
        name: '膨胀陈登珊瑚菌',
        pinyin: 'pzcdshj',
        starter: MushroomChildIds.SHAN_HU,
        wood: Woods.LV_SONG,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
    },
    {
        id: 'shanhu14',
        name: '膨胀贾诩珊瑚菌',
        pinyin: 'pzjxshj',
        starter: MushroomChildIds.SHAN_HU,
        wood: Woods.LV_SONG,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'shanhu15',
        name: '缩水董奉珊瑚菌',
        pinyin: 'ssdfshj',
        starter: MushroomChildIds.SHAN_HU,
        wood: Woods.LV_SONG,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'shanhu16',
        name: '缩水贾诩珊瑚菌',
        pinyin: 'ssjxshj',
        starter: MushroomChildIds.SHAN_HU,
        wood: Woods.JIAN_CI,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'shanhu17',
        name: '膨胀张郃珊瑚菌',
        pinyin: 'pzzhshj',
        starter: MushroomChildIds.SHAN_HU,
        wood: Woods.JIAN_CI,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'shanhu18',
        name: '缩水陈登珊瑚菌',
        pinyin: 'sscdshj',
        starter: MushroomChildIds.SHAN_HU,
        wood: Woods.JIAN_CI,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
];

const LABA_MUSHROOMS: MushroomDef[] = [
    {
        id: 'laba0',
        name: '未能长大的喇叭菌',
        pinyin: 'wnzddlbj',
        starter: MushroomChildIds.LABA,
        special: SpecialConditions.BUG,
        save: false,
    },
    {
        id: 'laba1',
        name: '寻常封心锁爱喇叭菌',
        pinyin: 'xcfxsalbj',
        starter: MushroomChildIds.LABA,
        wood: Woods.FENG,
        light: Lights.HUO,
    },
    {
        id: 'laba2',
        name: '寻常黄金喇叭菌',
        pinyin: 'xchjlbj',
        starter: MushroomChildIds.LABA,
        wood: Woods.FENG,
        light: Lights.HUO,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'laba3',
        name: '寻常陷阵营喇叭菌',
        pinyin: 'xcxzylbj',
        starter: MushroomChildIds.LABA,
        wood: Woods.FENG,
        light: Lights.HUO,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'laba4',
        name: '小巧黄金喇叭菌',
        pinyin: 'xqhjlbj',
        starter: MushroomChildIds.LABA,
        wood: Woods.GE_TENG,
        humidifier: Humidifiers.NIAO,
    },
    {
        id: 'laba5',
        name: '寻常超火爆喇叭菌',
        pinyin: 'xcchblbj',
        starter: MushroomChildIds.LABA,
        wood: Woods.GE_TENG,
        humidifier: Humidifiers.NIAO,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'laba6',
        name: '特大黄金喇叭菌',
        pinyin: 'tdhjlbj',
        starter: MushroomChildIds.LABA,
        wood: Woods.GE_TENG,
        humidifier: Humidifiers.NIAO,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'laba7',
        name: '小巧封心锁爱喇叭菌',
        pinyin: 'xqfxsalbj',
        starter: MushroomChildIds.LABA,
        wood: Woods.JIAN_CI,
        light: Lights.TONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'laba8',
        name: '特大超火爆喇叭菌',
        pinyin: 'tdchblbj',
        starter: MushroomChildIds.LABA,
        wood: Woods.JIAN_CI,
        light: Lights.TONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'laba9',
        name: '小巧青春痘喇叭菌',
        pinyin: 'xqqcdlbj',
        starter: MushroomChildIds.LABA,
        wood: Woods.JIAN_CI,
        light: Lights.TONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'laba10',
        name: '寻常夕阳喇叭菌',
        pinyin: 'xcxylbj',
        starter: MushroomChildIds.LABA,
        wood: Woods.JIAN_CI,
        light: Lights.HUO,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'laba11',
        name: '寻常青春痘喇叭菌',
        pinyin: 'xcqcdlbj',
        starter: MushroomChildIds.LABA,
        wood: Woods.JIAN_CI,
        light: Lights.HUO,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'laba12',
        name: '小巧超火爆喇叭菌',
        pinyin: 'xqchblbj',
        starter: MushroomChildIds.LABA,
        wood: Woods.JIAN_CI,
        light: Lights.HUO,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'laba13',
        name: '特大青春痘喇叭菌',
        pinyin: 'tdqcdlbj',
        starter: MushroomChildIds.LABA,
        wood: Woods.LV_SONG,
        light: Lights.HUO,
        humidifier: Humidifiers.BLUE,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'laba14',
        name: '特大封心锁爱喇叭菌',
        pinyin: 'tdfxsalbj',
        starter: MushroomChildIds.LABA,
        wood: Woods.LV_SONG,
        light: Lights.HUO,
        humidifier: Humidifiers.BLUE,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'laba15',
        name: '小巧陷阵营喇叭菌',
        pinyin: 'xqxzylbj',
        starter: MushroomChildIds.LABA,
        wood: Woods.LV_SONG,
        light: Lights.HUO,
        humidifier: Humidifiers.BLUE,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'laba16',
        name: '特大陷阵营喇叭菌',
        pinyin: 'tdxzylbj',
        starter: MushroomChildIds.LABA,
        wood: Woods.LV_SONG,
        light: Lights.TONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'laba17',
        name: '小巧夕阳喇叭菌',
        pinyin: 'xqxylbj',
        starter: MushroomChildIds.LABA,
        wood: Woods.LV_SONG,
        light: Lights.TONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'laba18',
        name: '特大夕阳喇叭菌',
        pinyin: 'tdxylbj',
        starter: MushroomChildIds.LABA,
        wood: Woods.LV_SONG,
        light: Lights.TONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
];

const DI_MUSHROOMS: MushroomDef[] = [
    {
        id: 'di0',
        name: '未能长大的地星菌',
        pinyin: 'wnzdddxj',
        starter: MushroomChildIds.DI,
        special: SpecialConditions.BUG,
        save: false,
    },
    {
        id: 'di1',
        name: '路边朴素地星菌',
        pinyin: 'lbpsdxj',
        starter: MushroomChildIds.DI,
        wood: Woods.FENG,
        light: Lights.HUO,
        humidifier: Humidifiers.ZHU,
    },
    {
        id: 'di2',
        name: '路边森系地星菌',
        pinyin: 'lbsxdxj',
        starter: MushroomChildIds.DI,
        wood: Woods.FENG,
        light: Lights.HUO,
        humidifier: Humidifiers.ZHU,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'di3',
        name: '路边荷塘夜色地星菌',
        pinyin: 'lbhtysdxj',
        starter: MushroomChildIds.DI,
        wood: Woods.FENG,
        light: Lights.HUO,
        humidifier: Humidifiers.ZHU,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'di4',
        name: '小只森系地星菌',
        pinyin: 'xzsxdxj',
        starter: MushroomChildIds.DI,
        wood: Woods.GE_TENG,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
    },
    {
        id: 'di5',
        name: '路边粉毛地星菌',
        pinyin: 'lbfmdxj',
        starter: MushroomChildIds.DI,
        wood: Woods.GE_TENG,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'di6',
        name: '巨型森系地星菌',
        pinyin: 'jxsxdxj',
        starter: MushroomChildIds.DI,
        wood: Woods.GE_TENG,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'di7',
        name: '小只朴素地星菌',
        pinyin: 'xzpsdxj',
        starter: MushroomChildIds.DI,
        wood: Woods.YAN,
        light: Lights.HUO,
    },
    {
        id: 'di8',
        name: '巨型粉毛地星菌',
        pinyin: 'jxfmdxj',
        starter: MushroomChildIds.DI,
        wood: Woods.YAN,
        light: Lights.HUO,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'di9',
        name: '小只轻骑兵地星菌',
        pinyin: 'xzqqbdxj',
        starter: MushroomChildIds.DI,
        wood: Woods.YAN,
        light: Lights.HUO,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'di10',
        name: '路边黄花菜地星菌',
        pinyin: 'lbhhcdxj',
        starter: MushroomChildIds.DI,
        wood: Woods.YAN,
    },
    {
        id: 'di11',
        name: '路边轻骑兵地星菌',
        pinyin: 'lbqqbdxj',
        starter: MushroomChildIds.DI,
        wood: Woods.YAN,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'di12',
        name: '小只粉毛地星菌',
        pinyin: 'xzfmdxj',
        starter: MushroomChildIds.DI,
        wood: Woods.YAN,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'di13',
        name: '巨型荷塘夜色地星菌',
        pinyin: 'jxhtysdxj',
        starter: MushroomChildIds.DI,
        wood: Woods.SHU,
        light: Lights.YU_RONG,
    },
    {
        id: 'di14',
        name: '小只黄花菜地星菌',
        pinyin: 'xzhhcdxj',
        starter: MushroomChildIds.DI,
        wood: Woods.SHU,
        light: Lights.YU_RONG,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'di15',
        name: '巨型黄花菜地星菌',
        pinyin: 'jxhhcdxj',
        starter: MushroomChildIds.DI,
        wood: Woods.SHU,
        light: Lights.YU_RONG,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'di16',
        name: '巨型轻骑兵地星菌',
        pinyin: 'jxqqbdxj',
        starter: MushroomChildIds.DI,
        wood: Woods.SHU,
    },
    {
        id: 'di17',
        name: '巨型朴素地星菌',
        pinyin: 'jxpsdxj',
        starter: MushroomChildIds.DI,
        wood: Woods.SHU,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'di18',
        name: '小只荷塘夜色地星菌',
        pinyin: 'xzhtysdxj',
        starter: MushroomChildIds.DI,
        wood: Woods.SHU,
        special: SpecialConditions.MUCH,
        save: true,
    },
];

const DEER_MUSHROOMS: MushroomDef[] = [
    {
        id: 'deer0',
        name: '未能长大的鹿角菌',
        pinyin: 'wnzddljj',
        starter: MushroomChildIds.DEER,
        special: SpecialConditions.BUG,
        save: false,
    },
    {
        id: 'deer1',
        name: '中庸素描鹿角菌',
        pinyin: 'zysmljj',
        starter: MushroomChildIds.DEER,
        wood: Woods.SONG,
    },
    {
        id: 'deer2',
        name: '中庸深渊鹿角菌',
        pinyin: 'zysyljj',
        starter: MushroomChildIds.DEER,
        wood: Woods.SONG,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'deer3',
        name: '中庸应援棒鹿角菌',
        pinyin: 'zyyybljj',
        starter: MushroomChildIds.DEER,
        wood: Woods.SONG,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'deer4',
        name: '微型深渊鹿角菌',
        pinyin: 'wxsyljj',
        starter: MushroomChildIds.DEER,
        wood: Woods.GE_TENG,
        light: Lights.HUO,
        humidifier: Humidifiers.NIAO,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'deer5',
        name: '中庸二刺螈鹿角菌',
        pinyin: 'zyecyljj',
        starter: MushroomChildIds.DEER,
        wood: Woods.GE_TENG,
        light: Lights.HUO,
        humidifier: Humidifiers.NIAO,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'deer6',
        name: '巨体深渊鹿角菌',
        pinyin: 'jtsyljj',
        starter: MushroomChildIds.DEER,
        wood: Woods.GE_TENG,
        light: Lights.HUO,
        humidifier: Humidifiers.NIAO,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'deer7',
        name: '中庸蔫蔫鹿角菌',
        pinyin: 'zynnljj',
        starter: MushroomChildIds.DEER,
        wood: Woods.YAN,
        light: Lights.HUO,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'deer8',
        name: '中庸碧玉鹿角菌',
        pinyin: 'zybyljj',
        starter: MushroomChildIds.DEER,
        wood: Woods.YAN,
        light: Lights.HUO,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'deer9',
        name: '微型二刺螈鹿角菌',
        pinyin: 'wxecyljj',
        starter: MushroomChildIds.DEER,
        wood: Woods.YAN,
        light: Lights.HUO,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'deer10',
        name: '巨体应援棒鹿角菌',
        pinyin: 'jtyybljj',
        starter: MushroomChildIds.DEER,
        wood: Woods.MING,
        light: Lights.YU_RONG,
    },
    {
        id: 'deer11',
        name: '微型蔫蔫鹿角菌',
        pinyin: 'wxnnljj',
        starter: MushroomChildIds.DEER,
        wood: Woods.MING,
        light: Lights.YU_RONG,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'deer12',
        name: '巨体蔫蔫鹿角菌',
        pinyin: 'jtnnljj',
        starter: MushroomChildIds.DEER,
        wood: Woods.MING,
        light: Lights.YU_RONG,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'deer13',
        name: '微型素描鹿角菌',
        pinyin: 'wxsmljj',
        starter: MushroomChildIds.DEER,
        wood: Woods.YAN,
        light: Lights.HUN,
        humidifier: Humidifiers.BLUE,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'deer14',
        name: '巨型二刺螈鹿角菌',
        pinyin: 'jxecyljj',
        starter: MushroomChildIds.DEER,
        wood: Woods.YAN,
        light: Lights.HUN,
        humidifier: Humidifiers.BLUE,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'deer15',
        name: '微型碧玉鹿角菌',
        pinyin: 'wxbyljj',
        starter: MushroomChildIds.DEER,
        wood: Woods.YAN,
        light: Lights.HUN,
        humidifier: Humidifiers.BLUE,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'deer16',
        name: '巨体碧玉鹿角菌',
        pinyin: 'jtbyljj',
        starter: MushroomChildIds.DEER,
        wood: Woods.MING,
    },
    {
        id: 'deer17',
        name: '巨体素描鹿角菌',
        pinyin: 'jtsmljj',
        starter: MushroomChildIds.DEER,
        wood: Woods.MING,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'deer18',
        name: '微型应援棒鹿角菌',
        pinyin: 'wxyybljj',
        starter: MushroomChildIds.DEER,
        wood: Woods.MING,
        special: SpecialConditions.MUCH,
        save: true,
    },
]

const CAI_MUSHROOMS: MushroomDef[] = [
    {
        id: 'cai0',
        name: '未能长大的菜菜菌',
        pinyin: 'wnzddccj',
        starter: MushroomChildIds.CAI,
        special: SpecialConditions.BUG,
        save: false,
    },
    {
        id: 'cai1',
        name: '通常西凉菜菜菌',
        pinyin: 'tcxlccj',
        starter: MushroomChildIds.CAI,
        wood: Woods.SONG,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
    },
    {
        id: 'cai2',
        name: '通常幽州菜菜菌',
        pinyin: 'tcyzccj',
        starter: MushroomChildIds.CAI,
        wood: Woods.SONG,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'cai3',
        name: '通常椰椰菜菜菌',
        pinyin: 'tcyyccj',
        starter: MushroomChildIds.CAI,
        wood: Woods.SONG,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'cai4',
        name: '小型幽州菜菜菌',
        pinyin: 'xxyzccj',
        starter: MushroomChildIds.CAI,
        wood: Woods.GE_TENG,
        light: Lights.HUO,
        time: TimeRanges.DAY,
    },
    {
        id: 'cai5',
        name: '通常水平太菜菜菌',
        pinyin: 'tcsptccj',
        starter: MushroomChildIds.CAI,
        wood: Woods.GE_TENG,
        light: Lights.HUO,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'cai6',
        name: '大型幽州菜菜菌',
        pinyin: 'dxyzccj',
        starter: MushroomChildIds.CAI,
        wood: Woods.GE_TENG,
        light: Lights.HUO,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'cai7',
        name: '小型西凉菜菜菌',
        pinyin: 'xxxlccj',
        starter: MushroomChildIds.CAI,
        wood: Woods.YAN,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'cai8',
        name: '大型水平太菜菜菜菌',
        pinyin: 'dxsptcccj',
        starter: MushroomChildIds.CAI,
        wood: Woods.YAN,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'cai9',
        name: '小型裂开菜菜菌',
        pinyin: 'xxlkccj',
        starter: MushroomChildIds.CAI,
        wood: Woods.YAN,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'cai10',
        name: '通常老菜菜菌',
        pinyin: 'tclccj',
        starter: MushroomChildIds.CAI,
        wood: Woods.YAN,
        light: Lights.HUN,
        time: TimeRanges.DAY,
    },
    {
        id: 'cai11',
        name: '通常裂开菜菜菌',
        pinyin: 'tclkccj',
        starter: MushroomChildIds.CAI,
        wood: Woods.YAN,
        light: Lights.HUN,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'cai12',
        name: '小型水平太菜菜菜菌',
        pinyin: 'xxsptcccj',
        starter: MushroomChildIds.CAI,
        wood: Woods.YAN,
        light: Lights.HUN,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'cai13',
        name: '大型椰椰菜菜菌',
        pinyin: 'dxyyccj',
        starter: MushroomChildIds.CAI,
        wood: Woods.SHU,
        light: Lights.DRAGON,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'cai14',
        name: '小型老菜菜菌',
        pinyin: 'xxlccj',
        starter: MushroomChildIds.CAI,
        wood: Woods.SHU,
        light: Lights.DRAGON,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'cai15',
        name: '大型老菜菜菌',
        pinyin: 'dxlccj',
        starter: MushroomChildIds.CAI,
        wood: Woods.SHU,
        light: Lights.DRAGON,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'cai16',
        name: '大型裂开菜菜菌',
        pinyin: 'dxlkccj',
        starter: MushroomChildIds.CAI,
        wood: Woods.SHU,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.BLUE,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'cai17',
        name: '大型西凉菜菜菌',
        pinyin: 'dxxlccj',
        starter: MushroomChildIds.CAI,
        wood: Woods.SHU,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.BLUE,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'cai18',
        name: '小型椰椰菜菜菌',
        pinyin: 'xxyyccj',
        starter: MushroomChildIds.CAI,
        wood: Woods.SHU,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.BLUE,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
];

const GHOST_MUSHROOMS: MushroomDef[] = [
    {
        id: 'ghost0',
        name: '未能长大的幽灵菌',
        pinyin: 'wnzddylj',
        starter: MushroomChildIds.GHOST,
        special: SpecialConditions.BUG,
        save: false,
    },
    {
        id: 'ghost1',
        name: '中号暗黑幽灵菌',
        pinyin: 'zhahylj',
        starter: MushroomChildIds.GHOST,
        wood: Woods.SONG,
        light: Lights.HUO,
    },
    {
        id: 'ghost2',
        name: '中号挑染幽灵菌',
        pinyin: 'zhtrylj',
        starter: MushroomChildIds.GHOST,
        wood: Woods.SONG,
        light: Lights.HUO,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'ghost3',
        name: '中号蓝天白云幽灵菌',
        pinyin: 'zhltbyylj',
        starter: MushroomChildIds.GHOST,
        wood: Woods.SONG,
        light: Lights.HUO,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'ghost4',
        name: '小号挑染幽灵菌',
        pinyin: 'xhtrylj',
        starter: MushroomChildIds.GHOST,
        wood: Woods.GE_TENG,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
    },
    {
        id: 'ghost5',
        name: '中号冰山幽灵菌',
        pinyin: 'zhbsylj',
        starter: MushroomChildIds.GHOST,
        wood: Woods.GE_TENG,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'ghost6',
        name: '大号挑染幽灵菌',
        pinyin: 'dhtrylj',
        starter: MushroomChildIds.GHOST,
        wood: Woods.GE_TENG,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'ghost7',
        name: '中号一口见阿祖幽灵菌',
        pinyin: 'zhykjazylj',
        starter: MushroomChildIds.GHOST,
        wood: Woods.YAN,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
    },
    {
        id: 'ghost8',
        name: '中号幻象幽灵菌',
        pinyin: 'zhhxylj',
        starter: MushroomChildIds.GHOST,
        wood: Woods.YAN,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'ghost9',
        name: '小号冰山幽灵菌',
        pinyin: 'xhbsylj',
        starter: MushroomChildIds.GHOST,
        wood: Woods.YAN,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'ghost10',
        name: '小号暗黑幽灵菌',
        pinyin: 'xhahylj',
        starter: MushroomChildIds.GHOST,
        wood: Woods.YAN,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
    },
    {
        id: 'ghost11',
        name: '大号冰山幽灵菌',
        pinyin: 'dhbsylj',
        starter: MushroomChildIds.GHOST,
        wood: Woods.YAN,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'ghost12',
        name: '小号幻象幽灵菌',
        pinyin: 'xhhxylj',
        starter: MushroomChildIds.GHOST,
        wood: Woods.YAN,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'ghost13',
        name: '大号幻象幽灵菌',
        pinyin: 'dhhxylj',
        starter: MushroomChildIds.GHOST,
        wood: Woods.SHU,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
    },
    {
        id: 'ghost14',
        name: '大号暗黑幽灵菌',
        pinyin: 'dhahylj',
        starter: MushroomChildIds.GHOST,
        wood: Woods.SHU,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'ghost15',
        name: '小号蓝天白云幽灵菌',
        pinyin: 'xhltbyylj',
        starter: MushroomChildIds.GHOST,
        wood: Woods.SHU,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'ghost16',
        name: '大号蓝天白云幽灵菌',
        pinyin: 'dhltbyylj',
        starter: MushroomChildIds.GHOST,
        wood: Woods.SHU,
        light: Lights.HUN,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
    },
    {
        id: 'ghost17',
        name: '小号一口见阿祖幽灵菌',
        pinyin: 'xhykjazylj',
        starter: MushroomChildIds.GHOST,
        wood: Woods.SHU,
        light: Lights.HUN,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'ghost18',
        name: '大号一口见阿祖幽灵菌',
        pinyin: 'dhykjazylj',
        starter: MushroomChildIds.GHOST,
        wood: Woods.SHU,
        light: Lights.HUN,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
];

const NIAO_MUSHROOMS: MushroomDef[] = [
    {
        id: 'niao0',
        name: '未能长大的鸟巢菌',
        pinyin: 'wnzddncj',
        starter: MushroomChildIds.NIAO,
        special: SpecialConditions.BUG,
        save: false,
    },
    {
        id: 'niao1',
        name: '超小型陶瓷鸟巢菌',
        pinyin: 'cxxtcncj',
        starter: MushroomChildIds.NIAO,
        wood: Woods.LOVE,
    },
    {
        id: 'niao2',
        name: '标准厨余鸟巢菌',
        pinyin: 'bzcyncj',
        starter: MushroomChildIds.NIAO,
        wood: Woods.LOVE,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'niao3',
        name: '超大型陶瓷鸟巢菌',
        pinyin: 'cdxtcncj',
        starter: MushroomChildIds.NIAO,
        wood: Woods.LOVE,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'niao4',
        name: '标准不可燃鸟巢菌',
        pinyin: 'bzbkrncj',
        starter: MushroomChildIds.NIAO,
        wood: Woods.CHANG_CHUN,
        light: Lights.HUO,
        humidifier: Humidifiers.NIAO,
        time: TimeRanges.DAY,
    },
    {
        id: 'niao5',
        name: '标准陶瓷鸟巢菌',
        pinyin: 'bztcncj',
        starter: MushroomChildIds.NIAO,
        wood: Woods.CHANG_CHUN,
        light: Lights.HUO,
        humidifier: Humidifiers.NIAO,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'niao6',
        name: '标准可燃鸟巢菌',
        pinyin: 'bzkrncj',
        starter: MushroomChildIds.NIAO,
        wood: Woods.CHANG_CHUN,
        light: Lights.HUO,
        humidifier: Humidifiers.NIAO,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'niao7',
        name: '超小型不可燃鸟巢菌',
        pinyin: 'cxxbkrncj',
        starter: MushroomChildIds.NIAO,
        wood: Woods.QING,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
    },
    {
        id: 'niao8',
        name: '超大型厨余鸟巢菌',
        pinyin: 'cdxcyncj',
        starter: MushroomChildIds.NIAO,
        wood: Woods.QING,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'niao9',
        name: '超小型木桩鸟巢菌',
        pinyin: 'cxxmzncj',
        starter: MushroomChildIds.NIAO,
        wood: Woods.QING,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'niao10',
        name: '超大型可燃鸟巢菌',
        pinyin: 'cdxkrncj',
        starter: MushroomChildIds.NIAO,
        wood: Woods.MING,
        light: Lights.DRAGON,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'niao11',
        name: '超小型五彩豆鸟巢菌',
        pinyin: 'cxxwcdncj',
        starter: MushroomChildIds.NIAO,
        wood: Woods.MING,
        light: Lights.DRAGON,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'niao12',
        name: '超大型五彩豆鸟巢菌',
        pinyin: 'cdxwcdncj',
        starter: MushroomChildIds.NIAO,
        wood: Woods.MING,
        light: Lights.DRAGON,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'niao13',
        name: '超大型木桩鸟巢菌',
        pinyin: 'cdxmzncj',
        starter: MushroomChildIds.NIAO,
        wood: Woods.MING,
        light: Lights.TONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'niao14',
        name: '超大型不可燃鸟巢菌',
        pinyin: 'cdxbkrncj',
        starter: MushroomChildIds.NIAO,
        wood: Woods.MING,
        light: Lights.TONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'niao15',
        name: '超小型可燃鸟巢菌',
        pinyin: 'cxxkrncj',
        starter: MushroomChildIds.NIAO,
        wood: Woods.MING,
        light: Lights.TONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'niao16',
        name: '标准五彩豆鸟巢菌',
        pinyin: 'bzwcdncj',
        starter: MushroomChildIds.NIAO,
        wood: Woods.QING,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
    },
    {
        id: 'niao17',
        name: '标准木桩鸟巢菌',
        pinyin: 'bzmzncj',
        starter: MushroomChildIds.NIAO,
        wood: Woods.QING,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'niao18',
        name: '超小型厨余鸟巢菌',
        pinyin: 'cxxcyncj',
        starter: MushroomChildIds.NIAO,
        wood: Woods.QING,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
];

const LING_MUSHROOMS: MushroomDef[] = [
    {
        id: 'ling0',
        name: '未能长大的美灵芝',
        pinyin: 'wnzddmlz',
        starter: MushroomChildIds.LING,
        special: SpecialConditions.BUG,
        save: false,
    },
    {
        id: 'ling1',
        name: '纤小红颜美灵芝',
        pinyin: 'xxhymlz',
        starter: MushroomChildIds.LING,
        wood: Woods.LOVE,
        light: Lights.HUO,
    },
    {
        id: 'ling2',
        name: '寻常滞销美灵芝',
        pinyin: 'xczxmlz',
        starter: MushroomChildIds.LING,
        wood: Woods.LOVE,
        light: Lights.HUO,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'ling3',
        name: '硕大红颜美灵芝',
        pinyin: 'sdhymlz',
        starter: MushroomChildIds.LING,
        wood: Woods.LOVE,
        light: Lights.HUO,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'ling4',
        name: '寻常瘦身美灵芝',
        pinyin: 'xcssmlz',
        starter: MushroomChildIds.LING,
        wood: Woods.CHANG_CHUN,
        light: Lights.HUN,
        humidifier: Humidifiers.NIAO,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'ling5',
        name: '寻常红颜美灵芝',
        pinyin: 'xchymlz',
        starter: MushroomChildIds.LING,
        wood: Woods.CHANG_CHUN,
        light: Lights.HUN,
        humidifier: Humidifiers.NIAO,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'ling6',
        name: '寻常阴湿美灵芝',
        pinyin: 'xcysmlz',
        starter: MushroomChildIds.LING,
        wood: Woods.CHANG_CHUN,
        light: Lights.HUN,
        humidifier: Humidifiers.NIAO,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'ling7',
        name: '纤小瘦身美灵芝',
        pinyin: 'xxssmlz',
        starter: MushroomChildIds.LING,
        wood: Woods.QING,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'ling8',
        name: '硕大滞销美灵芝',
        pinyin: 'sdzxmlz',
        starter: MushroomChildIds.LING,
        wood: Woods.QING,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'ling9',
        name: '纤小苍白美灵芝',
        pinyin: 'xxcbmlz',
        starter: MushroomChildIds.LING,
        wood: Woods.QING,
        light: Lights.HUN,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'ling10',
        name: '寻常潮人美灵芝',
        pinyin: 'xccrmlz',
        starter: MushroomChildIds.LING,
        wood: Woods.QING,
        light: Lights.HUN,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
    },
    {
        id: 'ling11',
        name: '寻常苍白美灵芝',
        pinyin: 'xccbmlz',
        starter: MushroomChildIds.LING,
        wood: Woods.QING,
        light: Lights.HUN,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'ling12',
        name: '纤小滞销美灵芝',
        pinyin: 'xxzxmlz',
        starter: MushroomChildIds.LING,
        wood: Woods.QING,
        light: Lights.HUN,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'ling13',
        name: '硕大阴湿美灵芝',
        pinyin: 'jdysmlz',
        starter: MushroomChildIds.LING,
        wood: Woods.GOLD,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.BLUE,
    },
    {
        id: 'ling14',
        name: '纤小潮人美灵芝',
        pinyin: 'xxcrmlz',
        starter: MushroomChildIds.LING,
        wood: Woods.GOLD,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.BLUE,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'ling15',
        name: '硕大潮人美灵芝',
        pinyin: 'sdcrmlz',
        starter: MushroomChildIds.LING,
        wood: Woods.GOLD,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.BLUE,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'ling16',
        name: '硕大苍白美灵芝',
        pinyin: 'xdcbmlz',
        starter: MushroomChildIds.LING,
        wood: Woods.GOLD,
    },
    {
        id: 'ling17',
        name: '硕大瘦身美灵芝',
        pinyin: 'sdssmlz',
        starter: MushroomChildIds.LING,
        wood: Woods.GOLD,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'ling18',
        name: '纤小阴湿美灵芝',
        pinyin: 'xxysmlz',
        starter: MushroomChildIds.LING,
        wood: Woods.GOLD,
        special: SpecialConditions.MUCH,
        save: true,
    },
];

const ZHU_MUSHROOMS: MushroomDef[] = [
    {
        id: 'zhu0',
        name: '未能长大的竹荪',
        pinyin: 'wnzddzs',
        starter: MushroomChildIds.ZHU,
        special: SpecialConditions.BUG,
        save: false,
    },
    {
        id: 'zhu1',
        name: '清淡莲藕味竹荪',
        pinyin: 'qdlowzs',
        starter: MushroomChildIds.ZHU,
        wood: Woods.LOVE,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
    },
    {
        id: 'zhu2',
        name: '适中猪肉味竹荪',
        pinyin: 'szzrwzs',
        starter: MushroomChildIds.ZHU,
        wood: Woods.LOVE,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'zhu3',
        name: '浓厚莲藕味竹荪',
        pinyin: 'nhlowzs',
        starter: MushroomChildIds.ZHU,
        wood: Woods.LOVE,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'zhu4',
        name: '适中黄花菜味竹荪',
        pinyin: 'szhhcwzs',
        starter: MushroomChildIds.ZHU,
        wood: Woods.CHANG_CHUN,
    },
    {
        id: 'zhu5',
        name: '适中莲藕味竹荪',
        pinyin: 'szlowzs',
        starter: MushroomChildIds.ZHU,
        wood: Woods.CHANG_CHUN,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'zhu6',
        name: '适中番茄味竹荪',
        pinyin: 'szfqwzs',
        starter: MushroomChildIds.ZHU,
        wood: Woods.CHANG_CHUN,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'zhu7',
        name: '适中蓝莓味竹荪',
        pinyin: 'szlmwzs',
        starter: MushroomChildIds.ZHU,
        wood: Woods.QING,
        light: Lights.HUO,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'zhu8',
        name: '适中墨鱼丸竹荪',
        pinyin: 'szmywzs',
        starter: MushroomChildIds.ZHU,
        wood: Woods.QING,
        light: Lights.HUO,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'zhu9',
        name: '清淡猪肉味竹荪',
        pinyin: 'qdzrwzs',
        starter: MushroomChildIds.ZHU,
        wood: Woods.QING,
        light: Lights.HUO,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'zhu10',
        name: '浓厚墨鱼丸竹荪',
        pinyin: 'nhmywzs',
        starter: MushroomChildIds.ZHU,
        wood: Woods.GOLD,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
    },
    {
        id: 'zhu11',
        name: '浓厚黄花菜味竹荪',
        pinyin: 'nhhhcwzs',
        starter: MushroomChildIds.ZHU,
        wood: Woods.GOLD,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'zhu12',
        name: '清淡番茄味竹荪',
        pinyin: 'qdfqwzs',
        starter: MushroomChildIds.ZHU,
        wood: Woods.GOLD,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'zhu13',
        name: '浓厚番茄味竹荪',
        pinyin: 'nhfqwzs',
        starter: MushroomChildIds.ZHU,
        wood: Woods.GOLD,
        light: Lights.HUN,
        humidifier: Humidifiers.BLUE,
        time: TimeRanges.DAY,
    },
    {
        id: 'zhu14',
        name: '清淡蓝莓味竹荪',
        pinyin: 'qdlmwzs',
        starter: MushroomChildIds.ZHU,
        wood: Woods.GOLD,
        light: Lights.HUN,
        humidifier: Humidifiers.BLUE,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'zhu15',
        name: '浓厚蓝莓味竹荪',
        pinyin: 'nhlmwzs',
        starter: MushroomChildIds.ZHU,
        wood: Woods.GOLD,
        light: Lights.HUN,
        humidifier: Humidifiers.BLUE,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'zhu16',
        name: '清淡黄花菜味竹荪',
        pinyin: 'qdhhcwzs',
        starter: MushroomChildIds.ZHU,
        wood: Woods.QING,
        light: Lights.HUN,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'zhu17',
        name: '浓厚猪肉味竹荪',
        pinyin: 'nhzrwzs',
        starter: MushroomChildIds.ZHU,
        wood: Woods.QING,
        light: Lights.HUN,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'zhu18',
        name: '清淡墨鱼丸竹荪',
        pinyin: 'qdmywzs',
        starter: MushroomChildIds.ZHU,
        wood: Woods.QING,
        light: Lights.HUN,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
];

const RUBY_MUSHROOMS: MushroomDef[] = [
    {
        id: 'ruby0',
        name: '未能长大的宝石菌',
        pinyin: 'wnzddbsj',
        starter: MushroomChildIds.RUBY,
        special: SpecialConditions.BUG,
        save: false,
    },
    {
        id: 'ruby1',
        name: '小小躺板板宝石菌',
        pinyin: 'xxtbbbsj',
        starter: MushroomChildIds.RUBY,
        wood: Woods.LOVE,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
    },
    {
        id: 'ruby2',
        name: '常规坏种宝石菌',
        pinyin: 'cghzbsj',
        starter: MushroomChildIds.RUBY,
        wood: Woods.LOVE,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'ruby3',
        name: '庞大躺板板宝石菌',
        pinyin: 'pdtbbbsj',
        starter: MushroomChildIds.RUBY,
        wood: Woods.LOVE,
        light: Lights.YU_RONG,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'ruby4',
        name: '常规番茄炒蛋宝石菌',
        pinyin: 'cgfqcdbsj',
        starter: MushroomChildIds.RUBY,
        wood: Woods.QIAN_NIU,
    },
    {
        id: 'ruby5',
        name: '常规躺板板宝石菌',
        pinyin: 'cgtbbbsj',
        starter: MushroomChildIds.RUBY,
        wood: Woods.QIAN_NIU,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'ruby6',
        name: '常规白切黑宝石菌',
        pinyin: 'cgbqhbsj',
        starter: MushroomChildIds.RUBY,
        wood: Woods.QIAN_NIU,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'ruby7',
        name: '常规酥酪宝石菌',
        pinyin: 'cgslbsj',
        starter: MushroomChildIds.RUBY,
        wood: Woods.JIAN_JING,
    },
    {
        id: 'ruby8',
        name: '常规夜光宝石菌',
        pinyin: 'cgygbsj',
        starter: MushroomChildIds.RUBY,
        wood: Woods.JIAN_JING,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'ruby9',
        name: '小小坏种宝石菌',
        pinyin: 'xxhzbsj',
        starter: MushroomChildIds.RUBY,
        wood: Woods.JIAN_JING,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'ruby10',
        name: '小小番茄炒蛋宝石菌',
        pinyin: 'xxfqcdbsj',
        starter: MushroomChildIds.RUBY,
        wood: Woods.JIAN_JING,
        light: Lights.DRAGON,
        humidifier: Humidifiers.NIAO,
    },
    {
        id: 'ruby11',
        name: '庞大坏种宝石菌',
        pinyin: 'pdhzbsj',
        starter: MushroomChildIds.RUBY,
        wood: Woods.JIAN_JING,
        light: Lights.DRAGON,
        humidifier: Humidifiers.NIAO,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'ruby12',
        name: '小小夜光宝石菌',
        pinyin: 'xxygbsj',
        starter: MushroomChildIds.RUBY,
        wood: Woods.JIAN_JING,
        light: Lights.DRAGON,
        humidifier: Humidifiers.NIAO,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'ruby13',
        name: '庞大夜光宝石菌',
        pinyin: 'pdygbsj',
        starter: MushroomChildIds.RUBY,
        wood: Woods.GOLD,
        light: Lights.TONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'ruby14',
        name: '庞大番茄炒蛋宝石菌',
        pinyin: 'pdfqcdbsj',
        starter: MushroomChildIds.RUBY,
        wood: Woods.GOLD,
        light: Lights.TONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'ruby15',
        name: '小小白切黑宝石菌',
        pinyin: 'xxbqhbsj',
        starter: MushroomChildIds.RUBY,
        wood: Woods.GOLD,
        light: Lights.TONG,
        humidifier: Humidifiers.ZHU,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'ruby16',
        name: '庞大白切黑宝石菌',
        pinyin: 'pdbqhbsj',
        starter: MushroomChildIds.RUBY,
        wood: Woods.GOLD,
        light: Lights.HUO,
        humidifier: Humidifiers.TAO,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'ruby17',
        name: '小小酥酪宝石菌',
        pinyin: 'xxslbsj',
        starter: MushroomChildIds.RUBY,
        wood: Woods.GOLD,
        light: Lights.HUO,
        humidifier: Humidifiers.TAO,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'ruby18',
        name: '庞大酥酪宝石菌',
        pinyin: 'pdslbsj',
        starter: MushroomChildIds.RUBY,
        wood: Woods.GOLD,
        light: Lights.HUO,
        humidifier: Humidifiers.TAO,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
]

const HOU_MUSHROOMS: MushroomDef[] = [
    {
        id: 'hou0',
        name: '未能长大的猴头菌',
        pinyin: 'wnzddhtj',
        starter: MushroomChildIds.HOU,
        special: SpecialConditions.BUG,
        save: false,
    },
    {
        id: 'hou1',
        name: '平凡社牛猴头菌',
        pinyin: 'pfsnhtj',
        starter: MushroomChildIds.HOU,
        wood: Woods.CHANG_CHUN,
        light: Lights.HUO,
    },
    {
        id: 'hou2',
        name: '平凡笨蛋猴头菌',
        pinyin: 'pfbdhtj',
        starter: MushroomChildIds.HOU,
        wood: Woods.CHANG_CHUN,
        light: Lights.HUO,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'hou3',
        name: '平凡宅宅猴头菌',
        pinyin: 'pfzzhtj',
        starter: MushroomChildIds.HOU,
        wood: Woods.CHANG_CHUN,
        light: Lights.HUO,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'hou4',
        name: '微小笨蛋猴头菌',
        pinyin: 'wxbdhtj',
        starter: MushroomChildIds.HOU,
        wood: Woods.GE_TENG,
        light: Lights.TONG,
        time: TimeRanges.NIGHT,
    },
    {
        id: 'hou5',
        name: '平凡高智商猴头菌',
        pinyin: 'pfgzshtj',
        starter: MushroomChildIds.HOU,
        wood: Woods.GE_TENG,
        light: Lights.TONG,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'hou6',
        name: '超级笨蛋猴头菌',
        pinyin: 'cjbdhtj',
        starter: MushroomChildIds.HOU,
        wood: Woods.GE_TENG,
        light: Lights.TONG,
        time: TimeRanges.NIGHT,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'hou7',
        name: '微小社牛猴头菌',
        pinyin: 'wxsnhtj',
        starter: MushroomChildIds.HOU,
        wood: Woods.QING,
        light: Lights.HUO,
        humidifier: Humidifiers.LIAN,
    },
    {
        id: 'hou8',
        name: '超级高智商猴头菌',
        pinyin: 'cjgzshtj',
        starter: MushroomChildIds.HOU,
        wood: Woods.QING,
        light: Lights.HUO,
        humidifier: Humidifiers.LIAN,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'hou9',
        name: '微小逃课猴头菌',
        pinyin: 'wxtkhtj',
        starter: MushroomChildIds.HOU,
        wood: Woods.QING,
        light: Lights.HUO,
        humidifier: Humidifiers.LIAN,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'hou10',
        name: '平凡隐鸢阁冠名猴头菌',
        pinyin: 'pfyyggmhtj',
        starter: MushroomChildIds.HOU,
        wood: Woods.QING,
    },
    {
        id: 'hou11',
        name: '平凡逃课猴头菌',
        pinyin: 'pftkhtj',
        starter: MushroomChildIds.HOU,
        wood: Woods.QING,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'hou12',
        name: '微小高智商猴头菌',
        pinyin: 'wxgzshtj',
        starter: MushroomChildIds.HOU,
        wood: Woods.QING,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'hou13',
        name: '超级逃课猴头菌',
        pinyin: 'cjtkhtj',
        starter: MushroomChildIds.HOU,
        wood: Woods.MING,
        light: Lights.HUO,
        humidifier: Humidifiers.NIAO,
        time: TimeRanges.DAY,
    },
    {
        id: 'hou14',
        name: '超级社牛猴头菌',
        pinyin: 'cjsnhtj',
        starter: MushroomChildIds.HOU,
        wood: Woods.MING,
        light: Lights.HUO,
        humidifier: Humidifiers.NIAO,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'hou15',
        name: '微小宅宅猴头菌',
        pinyin: 'wxzzhtj',
        starter: MushroomChildIds.HOU,
        wood: Woods.MING,
        light: Lights.HUO,
        humidifier: Humidifiers.NIAO,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
    {
        id: 'hou16',
        name: '超级宅宅猴头菌',
        pinyin: 'cjzzhtj',
        starter: MushroomChildIds.HOU,
        wood: Woods.MING,
        light: Lights.HUN,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
    },
    {
        id: 'hou17',
        name: '微小隐鸢阁冠名猴头菌',
        pinyin: 'wxyyggmhtj',
        starter: MushroomChildIds.HOU,
        wood: Woods.MING,
        light: Lights.HUN,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.LESS,
        save: true,
    },
    {
        id: 'hou18',
        name: '超级隐鸢阁冠名猴头菌',
        pinyin: 'wxgzshtj',
        starter: MushroomChildIds.HOU,
        wood: Woods.MING,
        light: Lights.HUN,
        humidifier: Humidifiers.LIAN,
        time: TimeRanges.DAY,
        special: SpecialConditions.MUCH,
        save: true,
    },
];

export const MUSHROOM_DB: MushroomDef[] = [
    ...CI_MUSHROOMS,
    ...MAO_MUSHROOMS,
    ...PAO_MUSHROOMS,
    ...CAO_MUSHROOMS,
    ...SHANHU_MUSHROOMS,
    ...LABA_MUSHROOMS,
    ...DI_MUSHROOMS,
    ...DEER_MUSHROOMS,
    ...CAI_MUSHROOMS,
    ...GHOST_MUSHROOMS,
    ...NIAO_MUSHROOMS,
    ...LING_MUSHROOMS,
    ...ZHU_MUSHROOMS,
    ...RUBY_MUSHROOMS,
    ...HOU_MUSHROOMS,
];